name: testing build
on: push
jobs:
  build-node:
    name: Build and run the test project
    runs-on: ubuntu-latest
    container: node:18.12.1
    steps:
      - run: node --version
        name: Check the Node Version
      - run: npm --version
        name: Check the NPM Version
      - uses: actions/checkout@v3
        name: Checkout Code from GitHub
      - uses: actions/setup-node@v3
        name: Checkout the node setup
      - run: npm install
        name: Install NPM packages